@Library('shared-lib-for-test') _

pipeline {
    agent none

    environment {
        // 공통 환경 변수 정의
        REGISTRY_HOST       = "${env.INSTANCE_REGISTRY_HOST}"
        REGISTRY_USER       = "${env.INSTANCE_REGISTRY_USER}"
        REGISTRY_PASSWORD   = "${env.INSTANCE_REGISTRY_PASSWORD}"
        GIT_USERNAME        = "${env.INSTANCE_GITLAB_USERNAME}"
        GIT_PASSWORD        = "${env.INSTANCE_GITLAB_TOKEN}"
        ARGOCD_SERVER       = "${env.INSTANCE_ARGOCD_SERVER}"
        ARGOCD_USERNAME     = "${env.INSTANCE_ARGOCD_USERNAME}"
        ARGOCD_PASSWORD     = "${env.INSTANCE_ARGOCD_PASSWORD}"

        // 프로젝트 관련 변수
        REPOSITORY          = "/shiftone-internal/jenkins-build-test"
        IMAGE_TAG           = "${env.GIT_COMMIT}"
        DOCKERFILE_PATH     = "${WORKSPACE}/Dockerfile"

        // ArgoCD 배포 관련 변수
        APP_NAME            = "${env.JOB_NAME}"
        CHART_PATH          = "helm"
        NAMESPACE           = "shiftone-internal"
        REGISTRY_REPO       = "${env.GIT_URL}.git"
    }

    stages {
        stage('build') {
            agent {
                kubernetes {
                    // 공통 라이브러리에서 Pod 템플릿 가져오기
                    yaml """
                    apiVersion: v1
                    kind: Pod
                    spec:
                    containers:
                    - name: kaniko
                      image: gcr.io/kaniko-project/executor:debug
                      imagePullPolicy: Always
                      tty: true
                    """
                }
            }
            steps {
                container('kaniko') {
                    script {
                        def builds = new BuildScript()
                        builds.kaniko()
                    }
                }
            }
        }
    }
}
