pipeline {
    parameters {
        string(name: 'NODE_VERSION', defaultValue: '20.4.0', description: 'Node.js version to use')
    }

    agent {
        docker {
            image "node:${params.NODE_VERSION}" // Use a Docker image that matches the specified Node.js version
            args '-u root:root' // Optional: run as root user if needed
        }
    }
    
    environment {
        ENV = 'dev'
        APP_NAME = 'my-react-app'
        BUILD_DIR = 'build'
        DEPLOY_DIR = "/path/${ENV}/mfa/apps/${APP_NAME}"
    }
    
    stages {
        stage('Prepare') {
            steps {
                echo 'Preparing build environment...'
                sh 'node --version'
                sh 'npm --version'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building React app...'
                sh 'npm ci'
                sh 'npm run build'
            }
        }
        
        stage('Deploy to MFA') {
            steps {
                echo 'Deploying to MFA structure...'
                sh "mkdir -p ${DEPLOY_DIR}"
                sh "cp -R ${BUILD_DIR}/* ${DEPLOY_DIR}"
            }
        }
        
        // stage('Cleanup') {
        //     steps {
        //         echo 'Cleaning up...'
        //         sh "rm -rf ${BUILD_DIR}"
        //     }
        // }
    }
    
    post {
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build or deployment failed.'
        }
    }
}
